# blacklist
branches:
  except:
    - check-haproxy
    
language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install . --use-mirrors
script: nosetests tests
before_script:
  - sudo apt-get install sysstat
  - curl -L https://github.com/downloads/elasticsearch/elasticsearch/elasticsearch-0.19.8.deb > /tmp/es.deb
  - sudo apt-get install haproxy
  - curl -L https://raw.github.com/DataDog/dd-agent/check-haproxy/tests/haproxy.cfg > /tmp/haproxy.cfg
  - curl -L https://github.com/downloads/elasticsearch/elasticsearch/elasticsearch-0.19.4.deb > /tmp/es.deb
  - sudo dpkg -i /tmp/es.deb
  - sudo service elasticsearch start
env:
  - DB=redis
notifications:
  irc:
    - "irc.freenode.org#datadog"
